receiver : Receiver.cpp
	g++ -std=c++11 Receiver.cpp -o receiver -lpthread 

thread : thread.cpp
	g++ thread.cpp -o thread -lpthread

transmitter : udp_transmitter.cpp
	g++ udp_transmitter.cpp -o transmitter -lpthread
